services:
  cockroachdb:
    image: cockroachdb/cockroach:v25.4.2
    command: start-single-node --insecure
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - cockroach-data:/cockroach/cockroach-data
    environment:
      COCKROACH_USER: home_environments_local
      COCKROACH_DATABASE: home_environments_local

volumes:
  cockroach-data:
